export const SEARCH_RESET = 'SEARCH_RESET';
export const SEARCH_IN_PROGRESS = 'SEARCH_IN_PROGRESS';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';
export const SEARCH_SET_QUERY_PENDING = 'SEARCH_SET_QUERY_PENDING';
export const SEARCH_SET_PAGE_NUMBER = 'SEARCH_SET_PAGE_NUMBER';
